// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/b488f3cb5f70ea62c66a3ecaef4e38baadf3727c/cors/index.d.ts
declare module 'cors' {
// Type definitions for cors
// Project: https://github.com/troygoode/node-cors/
// Definitions by: Mihhail Lapushkin <https://github.com/mihhail-lapushkin/>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped




import express = require('express');

namespace e {
    interface CorsOptions {
        origin?: any;
        methods?: any;
        allowedHeaders?: any;
        exposedHeaders?: any;
        credentials?: boolean;
        maxAge?: number;
        preflightContinue?: boolean;
    }
}

function e(options?: e.CorsOptions): express.RequestHandler;
export = e;
}
